# database init, supports mysql too
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/spec2?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
  jpa:
    hibernate:
      ddl-auto: none

spring.jackson.serialization.write_dates_as_timestamps: false
